os: linux
sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py,simplejson,devel,lowest
    - python: 3.5
      env: TOXENV=py
    - python: 3.4
      env: TOXENV=py
    - python: pypy
      env: TOXENV=py
    - python: nightly
      env: TOXENV=py
    - os: osx
      language: generic
      env: TOXENV=py
  allow_failures:
    - python: nightly
      env: TOXENV=py
    - os: osx
      language: generic
      env: TOXENV=py
  fast_finish: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install python3;
      virtualenv -p python3 ~/py-env;
      . ~/py-env/bin/activate;
    fi

install:
  - pip install tox

script:
  - tox

cache:
  - pip

branches:
  only:
    - master
    - /^.*-maintenance$/
